dance_gavin_dance = Artist.create(name: "Dance Gavin Dance", genre: "Post-Hardcore")
sleep_token = Artist.create(name: "Sleep Token", genre: "Hard Rock")
the_1975 = Artist.create(name: "The 1975", genre: "Dance-Rock")
greyhaven = Artist.create(name: "Greyhaven", genre: "Metal")
every_time_i_die = Artist.create(name: "Every Time I Die", genre: "Metal")
louis_cole = Artist.create(name: "Louis Cole", genre: "Jazz Pop")
bill_wurtz = Artist.create(name: "Bill Wurtz", genre: "Outsider Pop")
cat_company = Artist.create(name: "Cat Company", genre: "Post-Hardcore")
marmozets = Artist.create(name: "Marmozets", genre: "Rock")
invalids = Artist.create(name: "Invalids", genre: "Math Rock")

fred = Guest.create(name: "Fred", age: 19, artist_id: 1, show_id: 1)
john = Guest.create(name: "John", age: 24, artist_id: 2, show_id: 2)
steve = Guest.create(name: "Steve", age: 39, artist_id: 3, show_id: 3)
maddy = Guest.create(name: "Maddy", age: 25, artist_id: 4, show_id: 4)
megan = Guest.create(name: "Megan", age: 27, artist_id: 5, show_id: 5)
molly = Guest.create(name: "Molly", age: 29, artist_id: 6, show_id: 6)
adam = Guest.create(name: "Adam", age: 31, artist_id: 7, show_id: 7)
harry = Guest.create(name: "Harry", age: 18, artist_id: 8, show_id: 8)
sally = Guest.create(name: "Sally", age: 21, artist_id: 9, show_id: 9)
sarah = Guest.create(name: "Sarah", age: 34, artist_id: 10, show_id: 10)
sam = Guest.create(name: "Sam", age: 33, artist_id: 2, show_id: 3)
samuel = Guest.create(name: "Samuel", age: 40, artist_id: 10, show_id: 8)
george = Guest.create(name: "George", age: 44, artist_id: 7, show_id: 5)
kylo = Guest.create(name: "Kylo", age: 25, artist_id: 3, show_id: 3)
haven = Guest.create(name: "Haven", age: 20, artist_id: 4, show_id: 10)
cole = Guest.create(name: "Cole", age: 22, artist_id: 9, show_id: 2)
bryan = Guest.create(name: "Bryan", age: 50, artist_id: 1, show_id: 1)
tina = Guest.create(name: "Tina", age: 55, artist_id: 10, show_id: 10)
zane = Guest.create(name: "Zane", age: 21, artist_id: 5, show_id: 6)
han = Guest.create(name: "Han", age: 60, artist_id: 7, show_id: 8)

the_crocodile = Show.create(venue_name: "The Crocodile", venue_city: "Seattle", venue_state: "Washington", date: "12/12/20")
real_art_tacoma = Show.create(venue_name: "Real Art Tacoma", venue_city: "Tacoma", venue_state: "Washington", date: "12/13/20")
el_corazon = Show.create(venue_name: "El Corazon", venue_city: "Seattle", venue_state: "Washington", date: "12/14/20")
showbox_sodo = Show.create(venue_name: "Showbow Sodo", venue_city: "Seattle", venue_state: "Washington", date: "12/15/20")
neptune_theatre = Show.create(venue_name: "Neptune Theatre", venue_city: "Seattle", venue_state: "Washington", date: "12/16/20")
chase_field = Show.create(venue_name: "Chase Field", venue_city: "Phoenix", venue_state: "Arizona", date: "12/17/20")
house_of_blues = Show.create(venue_name: "House of Blues", venue_city: "Anaheim", venue_state: "California", date: "12/18/20")
florida_theatre = Show.create(venue_name: "Florida Theatre", venue_city: "Jacksonville", venue_state: "Florida", date: "12/19/20")
the_masquerade = Show.create(venue_name: "The Masquerade", venue_city: "Atlanta", venue_state: "Georgia", date: "12/20/20")
ford_park = Show.create(venue_name: "Ford Park", venue_city: "Beaumont", venue_state: "Texas", date: "12/21/20")

puts "Seeds are done"

